get:
  tags:
    - Product
  summary: Get product by ID
  operationId: GetProduct
  description: |
    Get product by ID
  responses:
    '200':
      description: Product data has been found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Product.yaml
    '401':
      description: Access forbidden
    '404':
      description: Not found
patch:
  tags:
    - Product
  summary: Update product data
  operationId: PatchProduct
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Product.yaml
  responses:
    '201':
      description: Product has been updated
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Product.yaml
    '401':
      description: Access forbidden
    '404':
      description: Not found
    '409':
      description: Product exists and can't be updated
    '422':
      description: Invalid data
delete:
  tags:
    - Product
  summary: Delete Product by ID
  operationId: DeleteProduct
  description: |
    Delete product by ID
  responses:
    '204':
      description: Product has been deleted
    '401':
      description: Access forbidden
    '402':
      description: Can't be deleted
    '404':
      description: Not found
